### ISSUE TITLE
How can I download genome data 'cds.fna' from NCBI?

### ISSUE THREAD

**Issue by cimutianxin** [1hachem/mutaGAN#1]
Hi @1hachem, following your step 3. install ncbi spike protein sequences (both proteomic and genomic sequences) using ncbi [datasets](https://www.ncbi.nlm.nih.gov/datasets/docs/) cli
`datasets download virus protein S`

I can only get protein sequences by the command, how did you get genomic sequences?

[NCBI doc](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-packages/virus-genome/) tells me that 

> (note: this package does not contain SARS-CoV-2 genome sequence)  

So how can I get 'cds.fna'?

Thanks!

**Comment by 1hachem** [comment]
Hello @cimutianxin 👋🏼

reading the [documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/datasets/download/virus/datasets_download_virus_protein/) in order to include the genomic data you should add the option `--include` with argument `cds`
```bash
datasets download virus protein S --include cds
```

**Comment by cimutianxin** [comment]
It works! Thanks a lot. 🤗

**Comment by 1hachem** [comment]
great ! you are welcome
